// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIiUXRiVLXr46cb9cMl1Y08z10drbmeuQ',
    appId: '1:688047279488:web:a415702e93446b07aa0565',
    messagingSenderId: '688047279488',
    projectId: 'portfolio-bce4c',
    authDomain: 'portfolio-bce4c.firebaseapp.com',
    storageBucket: 'portfolio-bce4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY26yzjrksG94h61x4IJmvTWzGdxli2bk',
    appId: '1:688047279488:android:f0704bed692c71faaa0565',
    messagingSenderId: '688047279488',
    projectId: 'portfolio-bce4c',
    storageBucket: 'portfolio-bce4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCupZUuHaq1neHDa9TUSLP3CT74_-UUORg',
    appId: '1:688047279488:ios:e2c49d2b78a9370daa0565',
    messagingSenderId: '688047279488',
    projectId: 'portfolio-bce4c',
    storageBucket: 'portfolio-bce4c.appspot.com',
    iosClientId: '688047279488-7ofruf5q1tb23eh8umbvu0obhrgapgqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
